name: Weblate - Create PR when weblate pushes changes
on:
  push: 
    branches: [weblate-sync]

jobs:
  weblateSync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
            branch: weblate-sync
            base: vp-rem
